### ISSUE TITLE
Clear up order+attribute design questions

### ISSUE THREAD

**Issue by matthampton-stock2shop** [stock2shop/console_v2#82]
- Order multiselect - what is the purpose?
- Order list has an icon for column settings but no design showing it open - might have to confirm this with designer
- Attribute Edit - How is the element type set?
                          - Can the data source be changed in-line in the table?
                          - How is value used?
- Attribute Add - looks like some fields are missing (relates to edit questions)
- List Data Sync - what does the "code" icon on each row do?

**Comment by flumonion** [comment]
> Order multiselect - what is the purpose?

So we can bulk add orders to a source.
You may also want to bulk change statuses of orders.
I see no icons have been provided by designer.
@matthampton-stock2shop do we have a issue to keep track of questions for the designer?

> Order list has an icon for column settings but no design showing it open - might have to confirm this with designer

Yes will confirm with designer.

>Attribute Edit - How is the element type set?
>- Can the data source be changed in-line in the table?
>- How is value used?

What do you mean by attribute edit?
Nothing on the order is editable except for qty, status and sending the order to source "create order" button.

>Attribute Add - looks like some fields are missing (relates to edit questions)

Can you post a screen shot of this add feature?

>List Data Sync - what does the "code" icon on each row do?

Can you post a screen shot of this?

**Comment by justinengle-krs** [comment]
@flumonion  I think the name of the issue is a bit confusing. It's not only for orders. Its for the other tabs as well. See below:


![image](https://user-images.githubusercontent.com/125956275/225010438-aa403672-105b-46f4-a373-4d89f988d041.png)
![image](https://user-images.githubusercontent.com/125956275/225010478-1104328f-1877-42d8-82b2-ccf0e5fb11bb.png)
![image](https://user-images.githubusercontent.com/125956275/225010584-740a12f1-2bce-4c10-ae83-ab1946249978.png)
